export interface RendD {
  U_RD_IdRD:           number;
  U_RD_RM_IdRendicion: number;
  U_RD_IdUsuario:      number;
  U_RD_Cuenta:         string | null;
  U_RD_NombreCuenta:   string | null;
  U_RD_Concepto:       string;
  U_RD_Importe:        number;
  U_RD_Descuento:      number;
  U_RD_TasaCero:       number | null;
  U_RD_N1:             string | null;
  U_RD_N2:             string | null;
  U_RD_N3:             string | null;
  U_RD_N4:             string | null;
  U_RD_N5:             string | null;
  U_RD_Proyecto:       string | null;
  U_RD_Fecha:          string;
  U_RD_IdTipoDoc:      number;
  U_RD_IdDoc:          number | null;
  U_RD_TipoDoc:        string;
  U_RD_Partida:        string | null;
  U_RD_Exento:         number | null;
  U_RD_Estado:         number;
  U_RD_ImpRet:         number | null;
  U_RD_Total:          number | null;
  U_RD_NumDocumento:   string | null;
  U_RD_NroAutor:       string | null;
  U_RD_Ctrl:           string | null;
  U_RD_NIT:            string;
  U_RD_CodProv:        string | null;
  U_RD_Prov:           string | null;
  U_MontoIVA:          number;
  U_MontoIT:           number;
  U_MontoIUE:          number;
  U_MontoRCIVA:        number;
  U_CuentaIVA:         string | null;
  U_CuentaIT:          string | null;
  U_CuentaIUE:         string | null;
  U_CuentaRCIVA:       string | null;
  U_ImporteBs:         number | null;
  U_EXENTOBS:          number | null;
  U_DESCTOBS:          number | null;
  U_RD_Marcado:        number;
  U_CTAEXENTO:         string;
  U_RD_AUXILIAR1:      string;
  U_RD_AUXILIAR2:      string;
  U_RD_AUXILIAR3:      string;
  U_RD_AUXILIAR4:      string;
  U_TASA:              number | null;
  U_CUF:               string | null;
  U_GIFTCARD:          number | null;
  U_ICE:               number;
  U_RD_NRO_OT:         string;
  U_RD_AdjuntosCount?: number;  // Campo virtual para conteo de adjuntos
}

export interface CreateRendDPayload {
  cuenta?:         string;
  nombreCuenta?:   string;
  concepto:        string;
  fecha:           string;
  idTipoDoc:       number;
  tipoDoc:         number;
  tipoDocName?:    string;
  idDoc?:          number;
  numDocumento?:   string;
  nroAutor?:       string;
  ctrl?:           string;
  cuf?:            string;
  importe:         number;
  descuento:       number;
  tasaCero?:       number;
  exento?:         number;
  impRet?:         number;
  total?:          number;
  importeBs?:      number;
  exentoBs?:       number;
  desctoBs?:       number;
  tasa?:           number;
  giftCard?:       number;
  montoIVA:        number;
  montoIT:         number;
  montoIUE:        number;
  montoRCIVA:      number;
  ice:             number;
  cuentaIVA?:      string;
  cuentaIT?:       string;
  cuentaIUE?:      string;
  cuentaRCIVA?:    string;
  ctaExento:       string;
  nit:             string;
  codProv?:        string;
  prov?:           string;
  n1?:             string;
  n2?:             string;
  n3?:             string;
  n4?:             string;
  n5?:             string;
  proyecto?:       string;
  partida?:        string;
  nroOT?:          string;
  auxiliar1?:      string;
  auxiliar2?:      string;
  auxiliar3?:      string;
  auxiliar4?:      string;
}

export type UpdateRendDPayload = Partial<CreateRendDPayload>;
